export const products = [
    {
      id: 1,
      title: "Logitech Pop keys Keyboard",
      description: "Pink in color",
      price: "9000",
      img: "https://resource.logitech.com/w_1001,c_limit,q_auto,f_auto,dpr_2.0/d_transparent.gif/content/dam/logitech/en/products/keyboards/pop-keys-wireless-mechanical/pop-keys-intro-heartbreaker-desktop-1.png?v=1",
      quantity: 1,
    },
    {
      id: 2,
      title: "Wireless charging mouse",
      description: "Copper in color",
      price: "2300",
      img: "https://i5.walmartimages.com/asr/b1fc528c-4bd8-44ba-835a-d9c42f7794db.b34c757f2557b69259b1c8b5b4414def.jpeg",
      quantity: 1,
    },
    {
      id: 3,
      title: "Table lamp",
      description: "black in color",
      price: "5000",
      img: "https://donlighting.com/wp-content/uploads/2019/10/ENDO-Table-Lamp-by-Pepe-Fornas-Ref.A-S1156DL-Foto1-600-800.jpg",
      quantity: 1,
    },
    {
      id: 4,
      title: "Book",
      description: "Aghori by Mayur Kalbag(Best seller) ",
      price: "300",
      img: "https://i.gr-assets.com/images/S/compressed.photo.goodreads.com/books/1626846951i/58599662._UY2560_SS2560_.jpg",
      quantity: 1,
    },
    {
      id: 5,
      title: "Rice Despenser",
      description: "Glass Rice Despenser",
      price: "25000",
      img: "https://m.media-amazon.com/images/I/71AuGsIT-+L._AC_SL1154_.jpg",
      quantity: 1,
    },
    {
      id: 6,
      title: "Headphones",
      description: "black in color",
      price: "5000",
      img: "https://images.philips.com/is/image/PhilipsConsumer/TAPH805BK_00-IMS-en_IN?$jpglarge$&wid=1250",
      quantity: 1,
    },
    {
      id: 7,
      title: "BTS x puma shoes",
      description: "BTS",
      price: "2500",
      img: "https://cdn.shopify.com/s/files/1/1553/5997/products/puma-x-bts-basket-patent-bts-shoes-957853.jpg?v=1657000532.png",
      quantity: 1,
    },
    {
      id: 8,
      title: "Laptop table",
      description: "Best for work from home ",
      price: "90500",
      img: "https://n1.sdlcdn.com/imgs/i/6/z/Story-Home-Premium-Height-Adjustable-SDL172389501-1-bd0d2.jpg",
      quantity: 1,
    },
    {
      id: 9,
      title: "Machbook",
      description: "macbook-pro-14-and-16",
      price: "250000",
      img: "https://www.apple.com/v/macbook-pro-14-and-16/b/images/meta/macbook-pro-14-and-16_overview__fz0lron5xyuu_og.png",
      quantity: 1,
    },
  ];